[project]
name = "coffee-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "asmabegum8450-debug", email = "asmabegum8450@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.11.2",
    "notebook>=7.6.3",
    "pandas>=3.0.6",
]

[project.scripts]
coffee-analysis = "coffee_analysis:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
